<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genProto/Dotw_ProtoBuf.proto

namespace Protobuffer\Dotwproto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protobuffer.dotwproto.HDReply.HotelStaticData.RoomTypeStaticData.RoomNames</code>
 */
class HDReply_HotelStaticData_RoomTypeStaticData_RoomNames extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 key = 1;</code>
     */
    private $key = 0;
    /**
     * Generated from protobuf field <code>repeated .protobuffer.dotwproto.HDReply.HotelStaticData.RoomTypeStaticData.RoomName roomName = 2;</code>
     */
    private $roomName;

    public function __construct() {
        \GPBMetadata\GenProto\DotwProtoBuf::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 key = 1;</code>
     * @return int
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>int32 key = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkInt32($var);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuffer.dotwproto.HDReply.HotelStaticData.RoomTypeStaticData.RoomName roomName = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoomName()
    {
        return $this->roomName;
    }

    /**
     * Generated from protobuf field <code>repeated .protobuffer.dotwproto.HDReply.HotelStaticData.RoomTypeStaticData.RoomName roomName = 2;</code>
     * @param \Protobuffer\Dotwproto\HDReply_HotelStaticData_RoomTypeStaticData_RoomName[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoomName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protobuffer\Dotwproto\HDReply_HotelStaticData_RoomTypeStaticData_RoomName::class);
        $this->roomName = $arr;

        return $this;
    }

}

