<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dotw.proto

namespace Dotw\Proto;

if (false) {
    /**
     * This class is deprecated. Use Dotw\Proto\Input\HotelFilters instead.
     * @deprecated
     */
    class Input_HotelFilters {}
}
class_exists(Input\HotelFilters::class);
@trigger_error('Dotw\Proto\Input_HotelFilters is deprecated and will be removed in the next major release. Use Dotw\Proto\Input\HotelFilters instead', E_USER_DEPRECATED);

