<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dotw.proto

namespace Dotw\Proto;

if (false) {
    /**
     * This class is deprecated. Use Dotw\Proto\Input\RoomOccupancy instead.
     * @deprecated
     */
    class Input_RoomOccupancy {}
}
class_exists(Input\RoomOccupancy::class);
@trigger_error('Dotw\Proto\Input_RoomOccupancy is deprecated and will be removed in the next major release. Use Dotw\Proto\Input\RoomOccupancy instead', E_USER_DEPRECATED);

