<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dotw.proto

namespace Dotw\Proto;

if (false) {
    /**
     * This class is deprecated. Use Dotw\Proto\Input\RoomTypeFilters instead.
     * @deprecated
     */
    class Input_RoomTypeFilters {}
}
class_exists(Input\RoomTypeFilters::class);
@trigger_error('Dotw\Proto\Input_RoomTypeFilters is deprecated and will be removed in the next major release. Use Dotw\Proto\Input\RoomTypeFilters instead', E_USER_DEPRECATED);

