<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dotw.proto

namespace Dotw\Proto;

if (false) {
    /**
     * This class is deprecated. Use Dotw\Proto\Input\SearchPeriodCriteria instead.
     * @deprecated
     */
    class Input_SearchPeriodCriteria {}
}
class_exists(Input\SearchPeriodCriteria::class);
@trigger_error('Dotw\Proto\Input_SearchPeriodCriteria is deprecated and will be removed in the next major release. Use Dotw\Proto\Input\SearchPeriodCriteria instead', E_USER_DEPRECATED);

