<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dotw.proto

namespace Dotw\Proto;

if (false) {
    /**
     * This class is deprecated. Use Dotw\Proto\Input\AdditionalFilters instead.
     * @deprecated
     */
    class Input_AdditionalFilters {}
}
class_exists(Input\AdditionalFilters::class);
@trigger_error('Dotw\Proto\Input_AdditionalFilters is deprecated and will be removed in the next major release. Use Dotw\Proto\Input\AdditionalFilters instead', E_USER_DEPRECATED);

