<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dotw.proto

namespace Dotw\Proto;

if (false) {
    /**
     * This class is deprecated. Use Dotw\Proto\Input\RoomCategory instead.
     * @deprecated
     */
    class Input_RoomCategory {}
}
class_exists(Input\RoomCategory::class);
@trigger_error('Dotw\Proto\Input_RoomCategory is deprecated and will be removed in the next major release. Use Dotw\Proto\Input\RoomCategory instead', E_USER_DEPRECATED);

