<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dotw.proto

namespace Dotw\Proto;

/**
 * Protobuf type <code>dotw.proto.ServerDotw</code>
 */
interface ServerDotwInterface
{
    /**
     * Method <code>psfilter</code>
     *
     * @param \Dotw\Proto\PsfilterRequest $request
     * @return \Dotw\Proto\PsfilterReply
     */
    public function psfilter(\Dotw\Proto\PsfilterRequest $request);

}

